export enum AccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE',
}

export enum JournalEntryStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
  REJECTED = 'REJECTED',
}

export enum JournalSourceType {
  MANUAL = 'MANUAL',
  PAYROLL = 'PAYROLL',
  REVENUE_RECOGNITION = 'REVENUE_RECOGNITION',
  INTERCOMPANY = 'INTERCOMPANY',
  BANK_IMPORT = 'BANK_IMPORT',
  SYSTEM_REVERSAL = 'SYSTEM_REVERSAL',
  CONSOLIDATION = 'CONSOLIDATION',
}

export enum PeriodStatus {
  OPEN = 'OPEN',
  SOFT_CLOSED = 'SOFT_CLOSED',
  LOCKED = 'LOCKED',
}

export enum UnitStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  ALLOCATED = 'ALLOCATED',
  UNDER_CONTRACT = 'UNDER_CONTRACT',
  HANDED_OVER = 'HANDED_OVER',
  SOLD = 'SOLD',
}

export enum ReconciliationStatus {
  UNRECONCILED = 'UNRECONCILED',
  PARTIALLY_RECONCILED = 'PARTIALLY_RECONCILED',
  RECONCILED = 'RECONCILED',
  DISPUTED = 'DISPUTED',
}
